// Copyright Epic Games, Inc. All Rights Reserved.

#include "Y2S1_Project1Character.h"
#include "Y2S1_Project1Projectile.h"
#include "Animation/AnimInstance.h"
#include "Camera/CameraComponent.h"
#include "Components/CapsuleComponent.h"
#include "Components/SkeletalMeshComponent.h"
#include "EnhancedInputComponent.h"
#include "EnhancedInputSubsystems.h"
#include "InputActionValue.h"
#include "TP_PickUpComponent.h"
#include "Engine/LocalPlayer.h"
#include "Kismet/KismetSystemLibrary.h"

DEFINE_LOG_CATEGORY(LogTemplateCharacter);

//////////////////////////////////////////////////////////////////////////
// AY2S1_Project1Character

AY2S1_Project1Character::AY2S1_Project1Character()
{
	// Character doesnt have a rifle at start
	bHasRifle = false;
	
	// Set size for collision capsule
	GetCapsuleComponent()->InitCapsuleSize(55.f, 96.0f);
		
	// Create a CameraComponent	
	FirstPersonCameraComponent = CreateDefaultSubobject<UCameraComponent>(TEXT("FirstPersonCamera"));
	FirstPersonCameraComponent->SetupAttachment(GetCapsuleComponent());
	FirstPersonCameraComponent->SetRelativeLocation(FVector(-10.f, 0.f, 60.f)); // Position the camera
	FirstPersonCameraComponent->bUsePawnControlRotation = true;

	// Create a mesh component that will be used when being viewed from a '1st person' view (when controlling this pawn)
	Mesh1P = CreateDefaultSubobject<USkeletalMeshComponent>(TEXT("CharacterMesh1P"));
	Mesh1P->SetOnlyOwnerSee(true);
	Mesh1P->SetupAttachment(FirstPersonCameraComponent);
	Mesh1P->bCastDynamicShadow = false;
	Mesh1P->CastShadow = false;
	//Mesh1P->SetRelativeRotation(FRotator(0.9f, -19.19f, 5.2f));
	Mesh1P->SetRelativeLocation(FVector(-30.f, 0.f, -150.f));

}

void AY2S1_Project1Character::Init_Implementation()
{
	// Call the base class  
	Super::BeginPlay();

	// Add Input Mapping Context
	if (APlayerController* PlayerController = Cast<APlayerController>(Controller))
	{
		if (UEnhancedInputLocalPlayerSubsystem* Subsystem = ULocalPlayer::GetSubsystem<UEnhancedInputLocalPlayerSubsystem>(PlayerController->GetLocalPlayer()))
		{
			Subsystem->AddMappingContext(DefaultMappingContext, 0);
		}
	}
	// OnTakeAnyDamage.AddDynamic(this, &AY2S1_Project1Character::HandleAnyDamage);
}


// void AY2S1_Project1Character::BeginPlay()
// {
// 	// Call the base class  
// 	Super::BeginPlay();
//
// 	// Add Input Mapping Context
// 	if (APlayerController* PlayerController = Cast<APlayerController>(Controller))
// 	{
// 		if (UEnhancedInputLocalPlayerSubsystem* Subsystem = ULocalPlayer::GetSubsystem<UEnhancedInputLocalPlayerSubsystem>(PlayerController->GetLocalPlayer()))
// 		{
// 			Subsystem->AddMappingContext(DefaultMappingContext, 0);
// 		}
// 	}
// 	// OnTakeAnyDamage.AddDynamic(this, &AY2S1_Project1Character::HandleAnyDamage);
// }

//////////////////////////////////////////////////////////////////////////// Input

void AY2S1_Project1Character::SetupPlayerInputComponent(UInputComponent* PlayerInputComponent)
{
	
	// Set up action bindings
	if (UEnhancedInputComponent* EnhancedInputComponent = Cast<UEnhancedInputComponent>(PlayerInputComponent))
	{
		// Jumping
		EnhancedInputComponent->BindAction(JumpAction, ETriggerEvent::Started, this, &ACharacter::Jump);
		EnhancedInputComponent->BindAction(JumpAction, ETriggerEvent::Completed, this, &ACharacter::StopJumping);

		// Moving
		EnhancedInputComponent->BindAction(MoveAction, ETriggerEvent::Triggered, this, &AY2S1_Project1Character::Move);

		// Looking
		EnhancedInputComponent->BindAction(LookAction, ETriggerEvent::Triggered, this, &AY2S1_Project1Character::Look);

		//Chardged Jump
		 EnhancedInputComponent->BindAction(ChargedJumpAction, ETriggerEvent::Triggered, this, &AY2S1_Project1Character::SuperJump);

		//Dash
		EnhancedInputComponent->BindAction(DashAction, ETriggerEvent::Triggered, this, &AY2S1_Project1Character::Dash);
	}
	else
	{
		UE_LOG(LogTemplateCharacter, Error, TEXT("'%s' Failed to find an Enhanced Input Component! This template is built to use the Enhanced Input system. If you intend to use the legacy system, then you will need to update this C++ file."), *GetNameSafe(this));
	}
}


void AY2S1_Project1Character::Move(const FInputActionValue& Value)
{

	// input is a Vector2D
	FVector2D MovementVector = Value.Get<FVector2D>();

	if (Controller != nullptr)
	{
		// add movement 
		AddMovementInput(GetActorForwardVector(), MovementVector.Y);
		AddMovementInput(GetActorRightVector(), MovementVector.X);
	}
}

void AY2S1_Project1Character::Look(const FInputActionValue& Value)
{
	// input is a Vector2D
	FVector2D LookAxisVector = Value.Get<FVector2D>();

	if (Controller != nullptr)
	{
		// add yaw and pitch input to controller
		AddControllerYawInput(LookAxisVector.X);
		AddControllerPitchInput(LookAxisVector.Y);
	}
}
void AY2S1_Project1Character::SuperJump(const FInputActionValue& Value)
{
	UE_LOG(LogTemp, Warning, TEXT("SUPERJUMP Triggered"))

	if (Controller != nullptr)
	{
		LaunchCharacter(GetActorUpVector() * SuperJumpPower, false, true);
		//add movement
	}
}
void AY2S1_Project1Character::Dash(const FInputActionValue& Value)
{
	UE_LOG(LogTemp, Warning, TEXT("DASH Triggered"));
	if (Controller != nullptr)
	{
		// SetActorLocation(GetActorLocation() * Dash_Offset);
		LaunchCharacter(GetActorForwardVector() * Dash_Offset, true, false);
		
	}
}


void AY2S1_Project1Character::SetHasRifle(bool bNewHasRifle)
{
	bHasRifle = bNewHasRifle;
}

bool AY2S1_Project1Character::GetHasRifle()
{
	return bHasRifle;
}
void AY2S1_Project1Character::NotifyActorBeginOverlap(AActor* otherActor)
{
	Super::NotifyActorBeginOverlap(otherActor);
	if (UKismetSystemLibrary::DoesImplementInterface(otherActor, UFirstInterface::StaticClass()))
	{
		//UE_LOG(LogTemp, Warning, TEXT("Executed"));
		IFirstInterface::Execute_Pickup(otherActor, Cast<AMyPlayerController>(this->GetController()));
		
	}
}






